# Generated by Django 4.2.1 on 2023-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapi', '0004_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
